# Generated by Django 4.2.6 on 2024-01-31 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_is_bloked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='FIO',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='user',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='user',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='комментарий'),
        ),
    ]
