# Generated by Django 5.0 on 2024-01-31 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='is_published',
            field=models.BooleanField(choices=[(True, 'Опубликовано'), (False, 'Неопубликовано')], default=True, verbose_name='признак публикации'),
        ),
    ]
