# Generated by Django 4.2.9 on 2024-02-03 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_on', models.TimeField(verbose_name='время рассылки от')),
                ('time_off', models.TimeField(verbose_name='время рассылки до')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время рассылки')),
                ('finish_date', models.DateField(blank=True, null=True, verbose_name='Дата завершения рассылки')),
                ('finish_time', models.TimeField(blank=True, null=True, verbose_name='Время завершения рассылки')),
                ('periodicity', models.CharField(choices=[('раз в день', 'раз в день'), ('раз в неделю', 'раз в неделю'), ('раз в месяц', 'раз в месяц')], max_length=100, verbose_name='переодичность рассылки')),
                ('status', models.CharField(choices=[('Создана', 'создана'), ('Запущена', 'запущена'), ('Завершена', 'завершена')], max_length=100, verbose_name='статус рассылки')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='название рассылки')),
                ('is_active', models.BooleanField(default=True, verbose_name='активность рассылки')),
                ('create_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
                'permissions': [('can_change_is_active_permission', 'Can change active latter')],
            },
        ),
        migrations.CreateModel(
            name='Сustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('name', models.CharField(max_length=300, verbose_name='ФИО')),
                ('comment', models.TextField(verbose_name='комментарий')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='тема письма')),
                ('message', models.TextField(verbose_name='тело письма')),
                ('user_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.сustomer', verbose_name='получатель сообщения')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время отправки')),
                ('status', models.CharField(max_length=100, verbose_name='статус попытки')),
                ('answer', models.BooleanField(verbose_name='ответ почтового сервера')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.сustomer', verbose_name='клиент рассылки')),
                ('mailing_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.letter', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'логи',
                'verbose_name_plural': 'логи',
            },
        ),
        migrations.AddField(
            model_name='letter',
            name='clients',
            field=models.ManyToManyField(to='service.сustomer', verbose_name='клиенты рассылки'),
        ),
        migrations.AddField(
            model_name='letter',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.message', verbose_name='сообщение'),
        ),
    ]
