# Generated by Django 5.0 on 2024-01-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='periodicity',
            field=models.IntegerField(choices=[('день', 'раз в день'), ('неделя', 'раз в неделю'), ('месяц', 'раз в месяц')], verbose_name='переодичность рассылки'),
        ),
    ]
