# Generated by Django 4.2.9 on 2024-02-03 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_message_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user_for',
        ),
    ]
