# Generated by Django 5.0 on 2024-01-05 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_letter_periodicity'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.сustomer', verbose_name='получатель сообщения'),
        ),
    ]
