# Generated by Django 5.0 on 2024-01-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_message_user_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='periodicity',
            field=models.CharField(choices=[('раз в день', 'раз в день'), ('раз в неделю', 'раз в неделю'), ('раз в месяц', 'раз в месяц')], max_length=100, verbose_name='переодичность рассылки'),
        ),
    ]
