# Generated by Django 5.0 on 2024-01-07 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_letter_periodicity'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='letter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.letter', verbose_name='настройка'),
        ),
    ]
