# Generated by Django 5.0 on 2024-01-29 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_message_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.сustomer', verbose_name='клиент рассылки'),
        ),
        migrations.AddField(
            model_name='logs',
            name='mailing_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.letter', verbose_name='рассылка'),
        ),
        migrations.RemoveField(
            model_name='letter',
            name='clients',
        ),
        migrations.AddField(
            model_name='letter',
            name='clients',
            field=models.ManyToManyField(to='service.сustomer', verbose_name='клиенты рассылки'),
        ),
    ]
