# Generated by Django 4.2.9 on 2024-02-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_remove_message_info_message_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='time_off',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='time_on',
        ),
        migrations.AlterField(
            model_name='letter',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True, verbose_name='Время рассылки'),
        ),
    ]
