# Generated by Django 4.2.9 on 2024-02-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_remove_letter_time_off_remove_letter_time_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='periodicity',
            field=models.CharField(choices=[('day', 'раз в день'), ('week', 'раз в неделю'), ('month', 'раз в месяц')], max_length=100, verbose_name='переодичность рассылки'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='status',
            field=models.CharField(choices=[('CREATED', 'создана'), ('STARTED', 'запущена'), ('COMPLETED', 'завершена')], max_length=100, verbose_name='статус рассылки'),
        ),
    ]
