# Generated by Django 5.0 on 2024-01-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_logs_client_logs_mailing_list_remove_letter_clients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='название рассылки'),
        ),
    ]
