# Generated by Django 5.0 on 2024-01-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_letter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='status',
            field=models.CharField(choices=[('Создана', 'создана'), ('Запущена', 'запущена'), ('Завершена', 'завершена')], max_length=100, verbose_name='статус рассылки'),
        ),
    ]
