# Generated by Django 5.0 on 2024-01-31 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_alter_letter_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letter',
            options={'permissions': [('can_change_is_active_permission', 'Can change active latter')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.AddField(
            model_name='letter',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активность рассылки'),
        ),
    ]
