# Generated by Django 4.2.9 on 2024-02-03 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_letter_author_сustomer_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='letter',
        ),
        migrations.AddField(
            model_name='letter',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.message', verbose_name='сообщение'),
        ),
    ]
