# Generated by Django 4.2.9 on 2024-02-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_alter_logs_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='last_mailing_time',
            field=models.DateTimeField(auto_now=True, verbose_name='время последней рассылки'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='date_time',
            field=models.TimeField(verbose_name='дата и время последней попытки'),
        ),
    ]
