# Generated by Django 4.2.9 on 2024-02-03 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_logs_last_mailing_time_alter_logs_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='last_mailing_time',
        ),
    ]
