# Generated by Django 4.2.9 on 2024-02-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_remove_logs_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='data_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время отправки'),
        ),
    ]
