# Generated by Django 4.2.9 on 2024-02-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0019_letter_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='finish_date',
            field=models.DateField(default='2024-01-01', verbose_name='Дата завершения рассылки'),
        ),
        migrations.AddField(
            model_name='letter',
            name='finish_time',
            field=models.TimeField(default='00:00', verbose_name='Время завершения рассылки'),
        ),
        migrations.AddField(
            model_name='letter',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True, verbose_name='Время рассылки'),
        ),
    ]
