# Generated by Django 4.2.9 on 2024-02-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_letter_finish_date_letter_finish_time_letter_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время рассылки'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='data_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время отправки'),
        ),
    ]
