# Generated by Django 4.2.9 on 2024-02-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0021_alter_letter_time_alter_logs_data_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='data_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Дата и время отправки'),
        ),
    ]
