# Generated by Django 4.2.9 on 2024-02-03 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0022_alter_logs_data_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='data_time',
        ),
    ]
