# Generated by Django 4.2.9 on 2024-02-03 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0023_remove_logs_data_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='create_date',
        ),
    ]
